# This file was generated by GoReleaser. DO NOT EDIT.
cask "yodo" do
  version "0.0.1-test.7"

  on_macos do
    on_intel do
      sha256 "e09833d994ee6deb182af12c0fbf85a47b44ef6855342260e6aeae6f96123c48"
      url "https://github.com/yodo-ai/yodo/releases/download/v#{version}/yodo-cli-#{version}-darwin-amd64.tar.gz",
        verified: "github.com/yodo-ai/yodo/"
    end
    on_arm do
      sha256 "17c582aee37337d0286b524979e4011222dec0bc958d41497edd97a5f88f0ab1"
      url "https://github.com/yodo-ai/yodo/releases/download/v#{version}/yodo-cli-#{version}-darwin-arm64.tar.gz",
        verified: "github.com/yodo-ai/yodo/"
    end
  end

  on_linux do
    on_intel do
      sha256 "a0d429d2a4bbfcd95022a85fa1ac822f39906567cdb186847bfb338029e235e0"
      url "https://github.com/yodo-ai/yodo/releases/download/v#{version}/yodo-cli-#{version}-linux-amd64.tar.gz",
        verified: "github.com/yodo-ai/yodo/"
    end
    on_arm do
      sha256 "96f4b225298a69326c405f9cfc70b6dbf7b850dbf50d21f6c42adcbd7eafc49c"
      url "https://github.com/yodo-ai/yodo/releases/download/v#{version}/yodo-cli-#{version}-linux-arm64.tar.gz",
        verified: "github.com/yodo-ai/yodo/"
    end
  end

  name "yodo"
  desc "Yodo CLI — tool for the Yodo platform"
  homepage "https://x.com/yida-ai/yodo"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "yodo"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/yodo"]
    end
  end

  # No zap stanza required

end
