# This file was generated by GoReleaser. DO NOT EDIT.
cask "yodo" do
  version "0.0.1-test.13"

  on_macos do
    on_intel do
      sha256 "e84f6f101e9d0217f9291c2f9d9e7af79057811cc91ea2248f1b0ec9014557aa"
      url "https://github.com/yodo-ai/yodo/releases/download/v#{version}/yodo-cli-#{version}-darwin-amd64.tar.gz",
        verified: "github.com/yodo-ai/yodo/"
    end
    on_arm do
      sha256 "9f0cad7af47dafe1e33734b36b57c5a6a13fb46f45d4d7336ffb4362147945de"
      url "https://github.com/yodo-ai/yodo/releases/download/v#{version}/yodo-cli-#{version}-darwin-arm64.tar.gz",
        verified: "github.com/yodo-ai/yodo/"
    end
  end

  on_linux do
    on_intel do
      sha256 "8f934de25df892200cd3e003182af393dd977df40e6d5541b40da30ebe4a8de4"
      url "https://github.com/yodo-ai/yodo/releases/download/v#{version}/yodo-cli-#{version}-linux-amd64.tar.gz",
        verified: "github.com/yodo-ai/yodo/"
    end
    on_arm do
      sha256 "2add6280faa4605d02d9b70e9f564b719bc5a43a7558b442a3e1c59a24cf9b16"
      url "https://github.com/yodo-ai/yodo/releases/download/v#{version}/yodo-cli-#{version}-linux-arm64.tar.gz",
        verified: "github.com/yodo-ai/yodo/"
    end
  end

  name "yodo"
  desc "Yodo CLI — tool for the Yodo platform"
  homepage "https://x.com/yida-ai/yodo"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "yodo"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/yodo"]
    end
  end

  # No zap stanza required

end
