# This file was generated by GoReleaser. DO NOT EDIT.
cask "yodo" do
  version "0.0.1-test.18"

  on_macos do
    on_intel do
      sha256 "1d94b1e1bfec9446e09dd525f21fdd1d37526f1e98f1a98179a3dad4913cb376"
      url "https://github.com/yodo-ai/yodo/releases/download/v#{version}/yodo-cli-#{version}-darwin-amd64.tar.gz",
        verified: "github.com/yodo-ai/yodo/"
    end
    on_arm do
      sha256 "bd5e98e5b146e910afbf3983ba8a054598f7b1d9e0186cbae2a1963d9846c6a0"
      url "https://github.com/yodo-ai/yodo/releases/download/v#{version}/yodo-cli-#{version}-darwin-arm64.tar.gz",
        verified: "github.com/yodo-ai/yodo/"
    end
  end

  on_linux do
    on_intel do
      sha256 "18e157f7c771fc7a7c0048fd3d4fcc3a00792295fae005701bb37aa541ac755b"
      url "https://github.com/yodo-ai/yodo/releases/download/v#{version}/yodo-cli-#{version}-linux-amd64.tar.gz",
        verified: "github.com/yodo-ai/yodo/"
    end
    on_arm do
      sha256 "0e8f6e81a03d32beba6c158dfad68b6dacea9191d4b900fc4460c32d5e5a761a"
      url "https://github.com/yodo-ai/yodo/releases/download/v#{version}/yodo-cli-#{version}-linux-arm64.tar.gz",
        verified: "github.com/yodo-ai/yodo/"
    end
  end

  name "yodo"
  desc "Yodo CLI — tool for the Yodo platform"
  homepage "https://x.com/yida-ai/yodo"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "yodo"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/yodo"]
    end
  end

  # No zap stanza required

end
